name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        distro: ['ubuntu-latest', 'debian-latest']

    steps:
    - uses: actions/checkout@v2
    
    - name: Run ShellCheck
      uses: ludeeus/action-shellcheck@master
      with:
        scandir: './scripts'

    - name: Run Unit Tests
      run: |
        cd tests
        ./run_tests.sh
